### ISSUE TITLE
Request: Latin letters glottal i/a/u: U+A7BA-U+A7BF

### ISSUE THREAD

**Issue by dwerning** [silnrsi/font-gentium#14]
Dear font developer team,

Egyptological community would be happy to see the following characters added:
U+A7BC LATIN CAPITAL LETTER GLOTTAL I
U+A7BD LATIN SMALL LETTER GLOTTAL I
= egyptological yod
![grafik](https://user-images.githubusercontent.com/33833393/187361266-c4f8b101-1520-4967-933c-a8e0e28a8b22.png)
The hook may be copied from the lower part of U+A723.
Note that, for capitals, the hook is to be placed before the capitals, not above it.

(Optionally, for Ugaritic purposes, it would be nice to also add analogous:)
U+A7BA LATIN CAPITAL LETTER GLOTTAL A
U+A7BB LATIN SMALL LETTER GLOTTAL A
U+A7BE LATIN CAPITAL LETTER GLOTTAL U
U+A7BF LATIN SMALL LETTER GLOTTAL U

Thank you for considering this request.

(This applies to [Charis SIL](https://github.com/silnrsi/font-charis/issues/9), Gentium Plus, and Andika alike.)

**Comment by jvgaultney** [comment]
Thanks - these are included in the next version

**Comment by jvgaultney** [comment]
Added in v6.200

**Comment by dwerning** [comment]
Thank you very much.
Now advertized on:  https://aaew.bbaw.de/egyptological-unicode-fonts
