### ISSUE TITLE
U+1078E MODIFIER LETTER SMALL REVERSED E mislocated at U+1088E in GentiumPlus-6.101

### ISSUE THREAD

**Issue by shenyileirob** [silnrsi/font-gentium#17]
U+1078E MODIFIER LETTER SMALL REVERSED E (𐞎) is mislocated at U+1088E in GentiumPlus-6.101.

**Comment by jvgaultney** [comment]
Oh! Thanks for catching that. We'll fix it in the next release.

**Comment by jvgaultney** [comment]
Fixed in v6.200
