### ISSUE TITLE
[Feature Request] Variable font

### ISSUE THREAD

**Issue by chromer030** [silnrsi/font-gentium#20]
Thanks for the font , it's great , any plan for a variable font  ?

**Comment by jvgaultney** [comment]
The next version of Gentium (v7) will change the project to be one single family of static fonts with additional weights. We've thought about then making that variable, however very few of our users have shown any interest in using it. Unless we have a solid base of users who would use a variable version we're not likely to make the effort.

How would you use a variable Gentium? Or would it be just as useful to have a set of static CSS weights (400, 500, 600, 700, 800)?

**Comment by chromer030** [comment]
My main reason to use variable fonts is having a single file containing all the possible variations with much lower size which enhance the website’s performance, responsiveness, and readability, also Variable fonts support CSS transition and animation.

**Comment by jvgaultney** [comment]
We're aware of the potential benefits, however if you're using only 1-2 weights the performance is actually better with static woff2 files. Is there some specific feature of variables that you would use today if you had Gentium Variable - use of a wide range of weights on a page, transition, animation, etc.?

**Comment by chromer030** [comment]
Currently i'm satisfied with static weights of gentium, and thanks for that. ❤️
This feature request was just for up-shifting this great font, to fulfill its presence in all forms of fonts.

**Comment by chromer030** [comment]
Closing the issue for now , we can reopen it when it's needed.
