### ISSUE TITLE
request for two new ligatures or kerning tuples

### ISSUE THREAD

**Issue by mirabilos** [silnrsi/font-gentium#24]
Severity: wishlist
Priority: low

Hi,

could you make the sequences…

- U+0054 U+2091 U+03C7
- U+004C U+1D2C U+0054 U+1D07 U+03A7
- and the combination U+0054 U+2091 U+03C7 U+002F U+004C U+1D2C U+0054 U+1D07 U+03A7

… render nicely? (I think how will be obvious.) They are already pretty decent, but could be slightly optimised, I guess.

**Comment by jvgaultney** [comment]
For those who may read this later, these sequences are an attempt to recreate the TeX and LaTeX logos:

![image](https://github.com/silnrsi/font-gentium/assets/4226750/59ff257b-f92d-4b35-8313-e77aaf5f44eb)

We won't be trying to make this look better, as it's really an incorrect way to encode them. According to longstanding tradition these logos are to be represented in text by macros `\TeX` and '\LaTeX'. If the rendering system can't handle that then plaintext TeX and LaTeX seem to be preferred (though some think a few of those letters should be Greek ones). [This Wikipedia article](https://en.wikipedia.org/wiki/LaTeX#Pronouncing_and_writing_.22LaTeX.22) says a bit about this.

As much as I love TeX (and XeTeX especially), I wouldn't want to add special ligatures for TeX, LaTeX, XeTeX, XeLaTeX, etc. Our OpenType code is already complex enough. But if we did it would be for the plaintext macro sequences.

**Comment by mirabilos** [comment]
Victor Gaultney dixit:

>We won't be trying to make this look better, as it's really an
>incorrect way to encode them.

It’s not, it’s the closest one can get to them using just UCS codepoints.

>According to longstanding tradition these
>logos are to be represented in text by macros `\TeX` and '\LaTeX'.

No, they cannot. These only work within those typesetting systems
themselves, but not e.g. for random text on webpages (where the
text may again be sourced from elsewhere).

bye,
//mirabilos
-- 
  "Using Lynx is like wearing a really good pair of shades: cuts out
   the glare and harmful UV (ultra-vanity), and you feel so-o-o COOL."
                                         -- Henry Nelson, March 1999

**Comment by jvgaultney** [comment]
I understand your desire to be able to display something that resembles the logos when the system does not support the traditional TeX macros. I can't see any reasonable way to do that with the UCS codepoints you're using.

The only way would be to add unique logo glyphs that are substituted for those sequences. If we did that we would choose to use the long-established sequences (\TeX, \LaTeX), not the sequences you suggest. Sorry - I'm just being a TeX purist. I would want to see either the proper TeX logo (using capital letters, with the proper vertical and horizontal kerns) to plaintext TeX.

Other people agree - [see this discussion](https://tex.stackexchange.com/questions/274362/what-unicode-characters-should-i-use-to-write-latex#:~:text=At%20least%20currently%2C%20there%20isn,around%20to%20match%20the%20logo.) that includes the opinion of a true TeX expert. 

We are, however, not planning to start adding logos to the fonts.

**Comment by mirabilos** [comment]
Victor Gaultney dixit:

>The only way would be to add unique logo glyphs that are substituted
>for those sequences. If we did that we would choose to use the
>long-established sequences (\TeX, \LaTeX), not the sequences you

No, that would be fatal. That’s what would also occur in regular
text and whose rendering MUST NOT be changed.

>We are, however, not planning to start adding logos to the fonts.

That’s fair.

To be honest, the current rendering is pretty nice already, but
slightly unbalanced. Mostly, in Lᴬ shift the ᴬ a tad to the left.
In Tₑχ, make the ₑ a tad larger, like it’s in the Fixed [Misc]
bitmap font, also to the left. That’s all that’s needed to make
it look balanced. I don’t need the exact representation of the
logo.

But I accept you don’t want these extra kerning pairs. I just
thought it would be worth asking.

bye,
//mirabilos
-- 
>> Why don't you use JavaScript? I also don't like enabling JavaScript in
> Because I use lynx as browser.
+1
	-- Octavio Alvarez, me and ⡍⠁⠗⠊⠕ (Mario Lang) on debian-devel
