### ISSUE TITLE
Support for Macedonian and Serbian localization (letters `б г д ѓ т`)

### ISSUE THREAD

**Issue by d125q** [silnrsi/font-gentium#3]
When it comes to the letters `б г д ѓ т`, Macedonian and Serbian have some differences in comparison to Russian, especially in italic type.  The picture below shows the differences using https://github.com/googlefonts/noto-fonts.  (Serbian is the same as Macedonian except it does not use the letter `ѓ`.)

It would be great if Gentium supported a similar style using the `locl` tag.

## Noto Serif and Sans

![Macedonian_Italics_Noto](https://user-images.githubusercontent.com/7765538/130425637-72539ffc-d3db-4fd6-947c-1d0eae5f03a3.png)

**Comment by jvgaultney** [comment]
Gentium Plus already has a `locl` feature for Serbian. See [Gentium Plus Font Features](https://software.sil.org/gentium/features/):

![image](https://user-images.githubusercontent.com/4226750/130427812-398b5297-9b8a-4f0c-a1b3-7998890b3720.png)

I'll look at adding a specific Macedonian feature to a future version.

**Comment by d125q** [comment]
Thank you — admittedly, I only tested for Macedonian support.  I suppose the only missing thing is the letter `ѓ` and the addition of MKD to `locl`.

**Comment by jvgaultney** [comment]
New `locl` feature added for Macedonian, and an additional new feature (cv84) that allows you to turn on Serbian/Macedonian forms for apps that do not support `locl` features. Both in v6.101.
