### ISSUE TITLE
Support for +sups, +subs, +sinf and +frac OpenType tags

### ISSUE THREAD

**Issue by RGB-es** [silnrsi/font-gentium#4]
Gentium Plus have all sub- and superscripts for numbers, but there is no OpenType option to quickly apply them, they need to be inserted as special characters. It would be really useful to have these options available for at least the numbers (and it would be great to have them for alphabetic characters too).

User case: set a style for footnote anchors that uses real superscripts instead of simulated ones.

**Comment by jvgaultney** [comment]
That's a nice idea. We're already planning on supporting 'frac' in a future release (one after the next) and could easily add 'sups' and 'subs' too (for numerals only). We probably won't support 'sinf' as in practice everyone seems to use 'subs'. 

Supporting 'sups' and 'subs' for alphabetic characters is much more involved, so we're not likely to add that anytime soon. I will add it to the list of longer-term requests. When you have a font with hundreds of letters adding hand-tweaked superscripts for everything adds a lot of extra size to the font and is a lot of work. Although we already do have sups and subs for those that are explicitly encoded in Unicode it would be confusing if the features only applied to certain letters and not others.

**Comment by jvgaultney** [comment]
(BTW - you don't need to make identical issues for Andika and Charis. If you make a suggestion for one we'll consider it for all of those fonts as we like to keep them similar in feature support except for style-specific features in Andika.)

**Comment by jvgaultney** [comment]
Added in v6.200, although we don't support +sinf as it is rarely used.
