### ISSUE TITLE
Documentation error: OpenType tags do not use parameters 

### ISSUE THREAD

**Issue by RGB-es** [silnrsi/font-gentium#5]
According to the documentation, this font dropped Graphite and now only offers OpenType features. In the `features.pdf` file, when presenting the available features, there is an error: for OpenType tags, parameters are ignored. Instead of using, as the documentation shows, `smcp=1` you only need to use `smcp` in order to get small caps. 

Tested on LibreOffice and XeTeX.

**Comment by bobh0303** [comment]
This is not a documentation error but we are listing an explicit value to provide maximum clarity. 

Note that, according to [css font feature settings](https://www.w3.org/TR/css-fonts-3/#propdef-font-feature-settings) documentation, the following feature setting values are all equivalent: 
- value is absent
- `1`
- `on`

> for OpenType tags, parameters are ignored.

Parameters (a.k.a feature setting values) are not ignored. It is just that if the parameter is absent then the assumed value is `1`

**Comment by RGB-es** [comment]
> Parameters (a.k.a feature setting values) are not ignored. It is just that if the parameter is absent then the assumed value is `1`

Well, XeLaTeX actually ignore them (they work in LibreOffice, though, I didn't know that, I learned something new!). Using any of the following codes in the preamble 

`\setmainfont[RawFeature={+ss01}]{Gentium Plus}`
`\setmainfont[RawFeature={+ss01=0}]{Gentium Plus}`
`\setmainfont[RawFeature={+ss01=1}]{Gentium Plus}`

gives the same result, i.e., single storey a and g (without the `+` _none_ of them gives single storey a and g).

**Comment by LornaSIL** [comment]
For XeLaTeX to use the features, you do need to use `\usepackage{fontspec}`
Then, I set this line: `\setmainfont[Renderer=OpenType,RawFeature={+ss01}]{Gentium Plus}`
and it is changing to the single story `a` and `g` for me.

I don't think it is necessary to set the "Renderer", but I do have it there.
