### ISSUE TITLE
Greek KORONIS U+1FBD improperly coerced to U+0343 COMBINING GREEK KORONIS behavior

### ISSUE THREAD

**Issue by tshinnic** [silnrsi/font-gentium#8]
While viewing text having a `U+03BB GREEK SMALL LETTER LAMDA` character (λ) followed by a `U+1FBD GREEK KORONIS` character (᾽) a great strangeness was seen.

A LAMBDA followed by KORONIS should look like just that, two separate characters:  λ᾽ 

Instead, what was seen closely resembles a LAMBDA *combined* with either a `U+0343 COMBINING GREEK KORONIS`  (&#x25CC;&#x0343;) or a `U+0313 COMBINING COMMA ABOVE` (&#x25CC;&#x0313;) - a LAMBDA with a comma as a hat.

Since that cannot be shown inline here using the Gentium Plus font, please see a [table of examples at Wikisource](https://en.wikisource.org/wiki/User:Shenme/GentiumPlus) demonstrating the appearance of different combinations of chars under Gentium Plus.

Key points:
1) a top hat variant for KORONIS is possible, but I've never actually seen it after transcribing more than a few texts from the 1800's, where instead the apostrophe-on-the-right-side form is uniformly (?) seen.
2) GREEK KORONIS is *not a combining character*. Gentium Plus is improperly forcing it to combine with the previous character, as seen in the examples - even with a Latin '7' character!?  (I think someone GSUB'd a U+0313?)
3) The combining KORONIS character is a different code point, `U+0343 COMBINING GREEK KORONIS` and actually the Unicode people would now prefer (?) use of `U+0313 COMBINING COMMA ABOVE`. *These are the combining characters*, not U+1FBD
4) The effect now seen can be and is more properly achieved by using the identified combining characters.
5) You spent effort to support the 'better' variant for [Greek circumflex](https://software.sil.org/gentium/features/), allowing users to avoid the tilde implementation seen so often in other fonts. This unusual appearance for KORONIS is much more jarring a deviation than the tilde circumflex ever was. 

U+1FBD GREEK KORONIS is not a combining character. It should return to being displayed as an isolated, separate character.

.
This observed on Windows 10, Chrome, Edge, and Firefox, using Gentium Plus from en.wikisource.org, where the [example](https://en.wikisource.org/wiki/User:Shenme/GentiumPlus) text is posted.

**Comment by jvgaultney** [comment]
Thanks, Tom, for the detailed report. We'll fix this soon. It may not get into the next release (6.1), but will certainly get into the one after that.

**Comment by jvgaultney** [comment]
Fixed in v6.101
